In [4]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots

In [5]:
gym= Table.read_table('megaGymDataset.csv')
gym

Unnamed: 0 | Title                         | Desc                                                         | Type     | BodyPart   | Equipment | Level        | Rating | RatingDesc
0          | Partner plank band row        | The partner plank band row is an abdominal exercise wher ... | Strength | Abdominals | Bands     | Intermediate | 0      | nan
1          | Banded crunch isometric hold  | The banded crunch isometric hold is an exercise targetin ... | Strength | Abdominals | Bands     | Intermediate | nan    | nan
2          | FYR Banded Plank Jack         | The banded plank jack is a variation on the plank that i ... | Strength | Abdominals | Bands     | Intermediate | nan    | nan
3          | Banded crunch                 | The banded crunch is an exercise targeting the abdominal ... | Strength | Abdominals | Bands     | Intermediate | nan    | nan
4          | Crunch                        | The crunch is a popular core exercise targeting the rect ... | Strength | Abdominals | Bands     | Intermediate | nan    | nan
5          | Decline band press sit-up     | The decline band press sit-up is a weighted core exercis ... | Strength | Abdominals | Bands     | Intermediate | nan    | nan
6          | FYR2 Banded Frog Pump         | nan                                                          | Strength | Abdominals | Bands     | Intermediate | nan    | nan
7          | Band low-to-high twist        | The band low-to-high twist is a core exercise targeting  ... | Strength | Abdominals | Bands     | Intermediate | nan    | nan
8          | Barbell roll-out              | The barbell roll-out is an abdominal exercise that utili ... | Strength | Abdominals | Barbell   | Intermediate | 8.9    | Average
9          | Barbell Ab Rollout - On Knees | The barbell roll-out is an abdominal exercise that utili ... | Strength | Abdominals | Barbell   | Intermediate | 8.9    | Average
... (2908 rows omitted)

In [6]:
exercises = gym.select("Title", "BodyPart", "Level", "Rating", "RatingDesc") 
exercises

Title                         | BodyPart   | Level        | Rating | RatingDesc
Partner plank band row        | Abdominals | Intermediate | 0      | nan
Banded crunch isometric hold  | Abdominals | Intermediate | nan    | nan
FYR Banded Plank Jack         | Abdominals | Intermediate | nan    | nan
Banded crunch                 | Abdominals | Intermediate | nan    | nan
Crunch                        | Abdominals | Intermediate | nan    | nan
Decline band press sit-up     | Abdominals | Intermediate | nan    | nan
FYR2 Banded Frog Pump         | Abdominals | Intermediate | nan    | nan
Band low-to-high twist        | Abdominals | Intermediate | nan    | nan
Barbell roll-out              | Abdominals | Intermediate | 8.9    | Average
Barbell Ab Rollout - On Knees | Abdominals | Intermediate | 8.9    | Average
... (2908 rows omitted)

In [8]:
body_part_abdominal= exercises.where('BodyPart', are.containing('Abdominals'))
body_part_abdominal

Title                         | BodyPart   | Level        | Rating | RatingDesc
Partner plank band row        | Abdominals | Intermediate | 0      | nan
Banded crunch isometric hold  | Abdominals | Intermediate | nan    | nan
FYR Banded Plank Jack         | Abdominals | Intermediate | nan    | nan
Banded crunch                 | Abdominals | Intermediate | nan    | nan
Crunch                        | Abdominals | Intermediate | nan    | nan
Decline band press sit-up     | Abdominals | Intermediate | nan    | nan
FYR2 Banded Frog Pump         | Abdominals | Intermediate | nan    | nan
Band low-to-high twist        | Abdominals | Intermediate | nan    | nan
Barbell roll-out              | Abdominals | Intermediate | 8.9    | Average
Barbell Ab Rollout - On Knees | Abdominals | Intermediate | 8.9    | Average
... (652 rows omitted)

In [9]:
body_part_abdominal_beg=body_part_abdominal.where('Level', are.containing('Beginner'))
body_part_abdominal_beg

Title                                  | BodyPart   | Level    | Rating | RatingDesc
Bench barbell roll-out                 | Abdominals | Beginner | 8.3    | Average
Barbell Side Bend                      | Abdominals | Beginner | 7      | Average
Advanced Kettlebell Windmill           | Abdominals | Beginner | 8.3    | Average
Kettlebell Pass Between The Legs       | Abdominals | Beginner | 7.3    | Average
Dumbbell spell caster                  | Abdominals | Beginner | 9.3    | Average
Plate Twist                            | Abdominals | Beginner | 9      | Average
Bosu Ball Cable Crunch With Side Bends | Abdominals | Beginner | 8.5    | Average
Cable reverse crunch                   | Abdominals | Beginner | 8.2    | Average
Cable Russian Twists                   | Abdominals | Beginner | 8.1    | Average
Cable Seated Crunch                    | Abdominals | Beginner | 7.7    | Average
... (19 rows omitted)

In [18]:
body_part_abdominal_beg_fl= body_part_abdominal_beg.where('Rating', are.above(6.9))
body_part_abdominal_beg_fl

Title                                  | BodyPart   | Level    | Rating | RatingDesc
Bench barbell roll-out                 | Abdominals | Beginner | 8.3    | Average
Barbell Side Bend                      | Abdominals | Beginner | 7      | Average
Advanced Kettlebell Windmill           | Abdominals | Beginner | 8.3    | Average
Kettlebell Pass Between The Legs       | Abdominals | Beginner | 7.3    | Average
Dumbbell spell caster                  | Abdominals | Beginner | 9.3    | Average
Plate Twist                            | Abdominals | Beginner | 9      | Average
Bosu Ball Cable Crunch With Side Bends | Abdominals | Beginner | 8.5    | Average
Cable reverse crunch                   | Abdominals | Beginner | 8.2    | Average
Cable Russian Twists                   | Abdominals | Beginner | 8.1    | Average
Cable Seated Crunch                    | Abdominals | Beginner | 7.7    | Average
... (6 rows omitted)

In [19]:
body_part_abdominal_beg_fl.show(16)

In [20]:
body_part_biceps= exercises.where('BodyPart', are.containing('Biceps'))
body_part_biceps

Title                                  | BodyPart | Level        | Rating | RatingDesc
Incline dumbbell biceps curl           | Biceps   | Intermediate | nan    | nan
Banded biceps curl in squat position   | Biceps   | Intermediate | nan    | nan
Banded Hammer Press - Gethin Variation | Biceps   | Intermediate | nan    | nan
Band standing concentration curl       | Biceps   | Intermediate | nan    | nan
Brachialis SMR                         | Biceps   | Beginner     | 3.2    | Average
Wide-grip barbell curl                 | Biceps   | Beginner     | 9.3    | Average
EZ-bar spider curl                     | Biceps   | Intermediate | 9.2    | Average
Barbell Curl                           | Biceps   | Intermediate | 9      | Average
Close-grip EZ-bar curl                 | Biceps   | Beginner     | 8.9    | Average
Preacher Curl                          | Biceps   | Intermediate | 8.8    | Average
... (158 rows omitted)

In [21]:
body_part_biceps_beg= body_part_biceps.where('Level', are.containing('Beginner'))
body_part_biceps_beg

Title                                        | BodyPart | Level    | Rating | RatingDesc
Brachialis SMR                               | Biceps   | Beginner | 3.2    | Average
Wide-grip barbell curl                       | Biceps   | Beginner | 9.3    | Average
Close-grip EZ-bar curl                       | Biceps   | Beginner | 8.9    | Average
Barbell Curls Lying Against An Incline       | Biceps   | Beginner | 8.8    | Average
Seated Close-Grip Concentration Barbell Curl | Biceps   | Beginner | 8.8    | Average
Close-grip barbell curl                      | Biceps   | Beginner | 8.6    | Average
Drag curl                                    | Biceps   | Beginner | 8.5    | Average
Lying High Bench Barbell Curl                | Biceps   | Beginner | 5.8    | Average
Seated wide-grip curl to close-grip curl     | Biceps   | Beginner | 0      | nan
Seated Straigh-Bar Curl Superset             | Biceps   | Beginner | 0      | nan
... (27 rows omitted)

In [22]:
body_part_biceps_beg_fl= body_part_biceps_beg.where('Rating', are.above(6.9))
body_part_biceps_beg_fl

Title                                        | BodyPart | Level    | Rating | RatingDesc
Wide-grip barbell curl                       | Biceps   | Beginner | 9.3    | Average
Close-grip EZ-bar curl                       | Biceps   | Beginner | 8.9    | Average
Barbell Curls Lying Against An Incline       | Biceps   | Beginner | 8.8    | Average
Seated Close-Grip Concentration Barbell Curl | Biceps   | Beginner | 8.8    | Average
Close-grip barbell curl                      | Biceps   | Beginner | 8.6    | Average
Drag curl                                    | Biceps   | Beginner | 8.5    | Average
Incline Hammer Curls                         | Biceps   | Beginner | 9.5    | Average
Biceps curl to shoulder press                | Biceps   | Beginner | 9.1    | Average
Flexor Incline Dumbbell Curls                | Biceps   | Beginner | 9      | Average
Cross-body hammer curl                       | Biceps   | Beginner | 8.9    | Average
... (20 rows omitted)

In [24]:
body_part_biceps_beg_fl.show(30)

In [25]:
body_part_quads= exercises.where('BodyPart', are.containing('Quadriceps'))
body_part_quads

Title                                     | BodyPart   | Level        | Rating | RatingDesc
Single-leg depth squat                    | Quadriceps | Intermediate | 9      | Average
Squats - With Bands                       | Quadriceps | Beginner     | 5.8    | Average
Hip Flexion with Band                     | Quadriceps | Beginner     | 0      | nan
Forward Band Walk                         | Quadriceps | Beginner     | 0      | nan
Boss Everline Resistance-Band Pull Sprint | Quadriceps | Intermediate | nan    | nan
Banded jump squat                         | Quadriceps | Intermediate | nan    | nan
Speed Box Squat                           | Quadriceps | Intermediate | nan    | nan
HM Banded Squat Toe Tap                   | Quadriceps | Intermediate | nan    | nan
UP Band Abducted Squat                    | Quadriceps | Intermediate | nan    | nan
FYR2 Lateral Band Walk                    | Quadriceps | Intermediate | nan    | nan
... (636 rows omitted)

In [26]:
body_part_quads_beg= body_part_quads.where('Level', are.containing('Beginner'))
body_part_quads_beg

Title                        | BodyPart   | Level    | Rating | RatingDesc
Squats - With Bands          | Quadriceps | Beginner | 5.8    | Average
Hip Flexion with Band        | Quadriceps | Beginner | 0      | nan
Forward Band Walk            | Quadriceps | Beginner | 0      | nan
Clean from Blocks            | Quadriceps | Beginner | 9.5    | Average
Hang Clean                   | Quadriceps | Beginner | 9.3    | Average
Olympic Squat                | Quadriceps | Beginner | 9.1    | Average
Box Squat with Bands         | Quadriceps | Beginner | 9      | Average
Weighted Jump Squat          | Quadriceps | Beginner | 9      | Average
Squat with Chains            | Quadriceps | Beginner | 9      | Average
Hang Clean - Below the Knees | Quadriceps | Beginner | 8.5    | Average
... (66 rows omitted)

In [27]:
body_part_quads_beg_fl= body_part_quads_beg.where('Rating', are.above(6.9))
body_part_quads_beg_fl

Title                        | BodyPart   | Level    | Rating | RatingDesc
Clean from Blocks            | Quadriceps | Beginner | 9.5    | Average
Hang Clean                   | Quadriceps | Beginner | 9.3    | Average
Olympic Squat                | Quadriceps | Beginner | 9.1    | Average
Box Squat with Bands         | Quadriceps | Beginner | 9      | Average
Weighted Jump Squat          | Quadriceps | Beginner | 9      | Average
Squat with Chains            | Quadriceps | Beginner | 9      | Average
Hang Clean - Below the Knees | Quadriceps | Beginner | 8.5    | Average
Split Jerk                   | Quadriceps | Beginner | 8.3    | Average
Jefferson Squats             | Quadriceps | Beginner | 8      | Average
Jerk Dip Squat               | Quadriceps | Beginner | 8      | Average
... (17 rows omitted)

In [29]:
bpq= body_part_quads_beg_fl.show(27)
bpq

In [33]:
bpq.bar('Rating')

AttributeError: 'NoneType' object has no attribute 'bar'